# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Animation' do
  pod 'InterpolatedAnimation', :path => '~/workspace/animation/InterpolatedAnimation'
end
